# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll", "~>4.0"

gem "webrick", "~> 1.7"

gem "jekyll-feed", "~> 0.17.0"

gem "jekyll-seo-tag","~>2.8.0"

gem "jekyll-sitemap","~>1.4.0"

gem "jekyll-paginate","~>1.1.0"

gem "jekyll-remote-theme","~>0.4.2"